# Change Shape methods
1. **reshape()**: This method returns a new tensor with the specified shape. If possible, <u>it shares the data with the original tensor to avoid copying</u>.
2. **view()**: Similar to **reshape()**, but it strictly returns <u>a vew of the original tensor with the new shape</u>. It requires the new shape to be compatible with the original tensor's layout.
3. **squeeze()**: This removes all dimensions of size 1 from the tensor.
4. **unsqueeze()**: This adds a dimension of size 1 at a specified index.
5. **transpose()**: This swaps two dimensions of the tensor.
6. **permute()**: This rearranges the dimensions of the tensor according to a given order.

In [ ]:
import torch

# Create an example tensor
x = torch.randn(2, 3) # Shape is (2, 3)
print("Original tensor:")
print(x)
print("Shape of original tensor: ", x.shape)

Original tensor:
tensor([[ 1.8675,  0.1820, -0.1222],
        [-0.1989, -0.0191, -1.2608]])
Shape of original tensor:  torch.Size([2, 3])


In [ ]:
# Using reshape to change shape
x_reshaped = x.reshape(3, 2)
print("Reshaped tensor (3, 2):")
print(x_reshaped)
print("Shape of reshaped tensor: ", x_reshaped.shape)

Reshaped tensor (3, 2):
tensor([[ 1.8675,  0.1820],
        [-0.1222, -0.1989],
        [-0.0191, -1.2608]])
Shape of reshaped tensor:  torch.Size([3, 2])


In [ ]:
# Using view to change shape
x_view = x.view(6)
print("View tensor (6):")
print(x_view)
print("Shape of view tensor: ", x_view.shape)

View tensor (6):
tensor([ 1.8675,  0.1820, -0.1222, -0.1989, -0.0191, -1.2608])
Shape of view tensor:  torch.Size([6])


In [ ]:
# Using squeeze to remove dimensions of size 1
x = torch.randn(1, 2, 3, 1)
print("Original tensor:")
print(x)
print("Shape of original tensor: ", x.shape)

x_squeeze = x.squeeze()
print("Squeezed tensor:")
print(x_squeeze)
print("Shape of squeezed tensor: ", x_squeeze.shape)

Original tensor:
tensor([[[[-0.6028],
          [ 0.5040],
          [ 0.4118]],

         [[-0.6902],
          [-0.3452],
          [-1.0556]]]])
Shape of original tensor:  torch.Size([1, 2, 3, 1])
Squeezed tensor:
tensor([[-0.6028,  0.5040,  0.4118],
        [-0.6902, -0.3452, -1.0556]])
Shape of squeezed tensor:  torch.Size([2, 3])


In [ ]:
# Using unsqueese to add a dimension of size 1
x_unsqueezed = x.squeeze().unsqueeze(0)
print("Unsqueezed tensor (add dimension at index 0):")
print(x_unsqueezed)
print("Shape of unsqueezed tensor: ", x_unsqueezed.shape)

Unsqueezed tensor (add dimension at index 0):
tensor([[[-0.6028,  0.5040,  0.4118],
         [-0.6902, -0.3452, -1.0556]]])
Shape of unsqueezed tensor:  torch.Size([1, 2, 3])


In [ ]:
print(x.shape)
# Using transpose to swap dimensions
x_transposed = x.transpose(1, 2) # Swap dimensions 1 and 2
print("Transposed tensor:")
print(x_transposed)
print("Shape of transposed tensor: ", x_transposed.shape)

torch.Size([1, 2, 3, 1])
Transposed tensor:
tensor([[[[-0.6028],
          [-0.6902]],

         [[ 0.5040],
          [-0.3452]],

         [[ 0.4118],
          [-1.0556]]]])
Shape of transposed tensor:  torch.Size([1, 3, 2, 1])


In [ ]:
print(x.shape)
# Using permute to rearrange dimenions
x_permuted = x.permute(2, 1, 3, 0)
print("Permuted tensor (rearrange dimensions):")
print(x_permuted)
print("Shape of permuted tensor: ", x_permuted.shape)

torch.Size([1, 2, 3, 1])
Permuted tensor (rearrange dimensions):
tensor([[[[-0.6028]],

         [[-0.6902]]],


        [[[ 0.5040]],

         [[-0.3452]]],


        [[[ 0.4118]],

         [[-1.0556]]]])
Shape of permuted tensor:  torch.Size([3, 2, 1, 1])


# reshape() vs. view()

## Difference between reshape() and view()
1. **Memory Layout Compatibility**:
    * **view()**: It requires the requested view to be contiguous(連続した) in memory. This means that the tensor and the desired new shape must preserve the order of the data such that each element is next to the previous element in the original tensor. If the original tensor is not contiguous, you will need to call **tensor.contiguous()** before calling **view()**.
    * **reshape()**: It can handle non-contiguous tensors directly by returning a view if possible, or otherwise copying the data to make it contiguous. This makes **reshape()** more versatile(多用途) if you're unsure about the memory layout of your tensor.
2. **Error Handling**:
    * **view()**: Throws an error if the tensor cannot be viewed in the new shape without altering its continuity.
    * **reshape()**: Attempts to return a tensor with the desired shape, and will <u>silently handle issues related to non-contiguity by copying the data</u> if necessary.


## When to Use `reshape()` vs. `view()`
* **Use `view()`**: When you are sure that the tensor is contiguous and you want to avoid any potential overhead from handling non-contiguous tensors. It's a bit stricter, enduring you're aware of the tensor's layout, which can help prevent subtle bugs in complex systems.
* **Use `reshape()`**: When you might be dealing with tensors that could be non-contiguous, or you're not sure about the tensor's memory layout. It's safer and more flexible because it handles the rearrangement of the data if necessary.


## Example to Illustrate
Consider a situation where you perform an operation that might make a tensor non-contiguous, like transposing dimensions. Here's how you might decide between **view()** and **reshape()**:

In [ ]:
import torch

# Creating tensor
x = torch.randn(2, 3)

# Transpose makes the tensor non-contiguous
x_t = x.transpose(0, 1)

try:
    # This will fail because x_t is not contiguous
    x_view = x_t.view(6)
except RuntimeError as e:
    print("Error using veiw:", e)

Error using veiw: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.


In [ ]:
# This will work because reshape handles non-contiguity
x_reshaped = x_t.reshape(6)
print("Reshaped tensor:", x_reshaped)

Reshaped tensor: tensor([-1.4226,  0.4395,  0.9415, -2.6417,  0.6951, -0.3336])


In this example, **reshape()** is the appropriate choice after transposing the tensor, as it seamlessly handles the non-contiguity. Use **view()** when you're dealing with simpler transformations or when you're certain of the tensor's continuity, such as after flattening operations that do not alter the order of the underlying data.

# Importance of Continuity of data in Memory

In PyTorch, the continuity of data in memory plays a crucial role because it directly affects how efficiently operations on tensors can be performed. Let's explore why data continuity is important and how it impacts tensor operations:


## 1. Efficiency of Memory Access
* **Contiguous tensors** store their elements in a single uninterrupted block of memory. This means that accessing the elements in sequence (the way many tensor operations do) is very fast because the elements are laid out sequentially in memory.
* **Non-contiguous tensors** do not store their elements in a single, linear block of memory. Instead, their storage maight skip over some parts of memory. This occurs, for example, after transposing a tensor or selecting a non-contiguous slice from a tensor. Accessing the elements of non-contiguous tensors can involve jumping around in memory, which is less efficient than linear memory access.


## 2. Optimization of Operations
* Many underlying libraries that PyTorch uses, such as those for BLAS (Basic Linear Algebra Subprograms) and LAPACK (Linear Algebra Package), are optimized for data that is contiguous in memory. These optimizations assume that data is stored in a predictable, sequential manner, which can significantly speed up operations like matrix multiplication, addition, and more.


## 3. Simplicity of Implementation
* Keeping data contiguous simplifies the implementation of complex operations. Developers writing low-level code can make assumptions about data layout that allow for simpler, faster code.
* Operations that change tensor shape, like reshaping, slicing, or transposing, can alter the contiguity of a tensor. Being able to handle these operations effectively while managing memory layout is a key part of designing efficient tensor computations.


## 4. Use of `view()** and Contiguity
* The **view()** operation in PyTorch is a light weight method to change the shape of a tensor without copying the data. It can <u>only be used when the new shape arrangement allows for a contiguous view of the data</u>. If this condition isn't met, attempting to use **view()** will result in an error.
** This restriction ensures that all **view()** operations are not only fast (as they avoid data copying) but also safe, in that they will not unintentionally lead to incorrect computations or inefficient memory access patterns.


## Practical Implications
When working with PyTorch, it's often important to check the contiguity of your tensors, especially after performing operations that might disrupt this property. You can check if a tensor is contiguous using **tensor.is_contiguous()** and make it contiguous with **tensor.contiguous()**. This can be particularly important before using **view()**, or when you are preparing tensors for operations that require high computational efficiency.

<br>

Understanding these aspects can help you optimize your PyTorch code for performance and correctness, especially in complex systems or deep learning models where large-scale data manipulation is common.

# Operation to break contiguity of data

## 1. Transposing Dimensions
* When you transpose a tensor, the underlying data is not rearranged; only the way the data is accessed changes. This usually results in a non-contiguous tensor.
* Example: **x.transpose(0, 1)**

## 2. Permuting Dimensions
* Similar to transposing, permuting the dimensions of a tensor changes how the data is indexed without moving the data itself, often resulting in a non-contiguous layout.
* Example: **x.permute(1, 0, 2)**

## 3. Selecting Non-sequential Slices
* When you slice a tensor in a non-standard step size or in multiple dimensions, the result might not conver a continuous block of memory.
* Example: **x[:, 0::2]** (slicing every other element)

## 4. Narrowing
* Narrowing a tensor to a subset of its original dimensions can create a non-contiguous tensor if the slice doesn't align with the original memory layout.
* Example: **x.narrow(0, 1, 3)**

## 5. Advanced Indexing
* Using non-sequential indices or masks to index into a tensor can result in a non-contiguous tensor because the resulting tensor does not correspond to a regular block of the original tensor.
* Example: **x[[2, 0. 3], :]** (indexing with a non-sequenctial list of indices)

## 6. Unfolding
* The unfold operation extracts sliding local blocks from a batched input tensor, which often results in non-contiguous output due to the way blocks are laid out in memory.
* Example: **x.unfold(dimension=0, size=2, step=1)**

## 7. Expanding
* When you expand a tensor, the size of one or more dimensions is increased without copying data, leading to repeated usage of the same data in memory. This generally results in a non-contiguous tensor because the logical structure of the tensor no longer matches a linear progression in memory.
* Example: **x.expand(-1, 4)**

## Practical Consideration
After performing any of these operations, if you need to ensure that a tensor is contiguous (for example, before using **view()**), you can use **tensor.contiguous()** to get a contiguous version of the tensor. This might involve copying the data if necessary. Always check tensor contiguity with **tensor.is_contiguous()** when performance and memory layout are critical concerns in your applidation.

# squeeze() & unsqueeze()'s effect to contiguity
Using **tensor.squeeze()** and **tensor.unsqueeze()** generally **does not** lead to loss of contiguity in the tensor data. These operations are exceptions to some of the other reshaping methods because they only modify the shape of the tensor without changing the order or the layout of the underlying data. Let's clarify how these work:

## tensor.unsuqeeze()
* **Adding a Dimension**: This operation adds a new dimension of size one at the specified index. Since it does not alter the order of existing elements and merely introduces an new axis, the data's contiguity is preserved. For example, if you have a tensor of shape **(3, 4)** and you use **unsqueeze(0)**, the new shape becomes **(1, 3, 4)**, but the underlying data layout in memory remains the same.

## tensor.squeeze()
* **Removing Single-Dimension Entries**: This operation removes all dimensions of size one, or a specific dimension if specified. Removing these singleton dimensions does not require rearrangeing the data; it just changes how the tensor's shape is interpreted. Thus, the data remains contiguous as long as the tensor was contiguous before the operation.

Here is a quick example to demonstrate that **unsqueese()** and **squeeze()** prserve contiguity:


In [ ]:
import torch

# Create a contiguous tensor
x = torch.randn(2, 3)
print(x.shape)

# Use unsuqeeze to add a dimension
x_unsqueezed = x.unsqueeze(0)
print("Is the unsqueeze tensor contiguous?", x_unsqueezed.is_contiguous())

# Use squeeze to remove single-dimension entries
x_squeezed = x_unsqueezed.squeeze(0)
print("Is the squeeze tensor contiguous?", x_squeezed.is_contiguous())

torch.Size([2, 3])
Is the unsqueeze tensor contiguous? True
Is the squeeze tensor contiguous? True


In the example, both **unsqueeze()** and **squeeze()** retain the contiguity of the tensor. This behavior makes these operations very efficient for adjusting tensor shapes, particularly when preparing data for input to neural networks or when aligning tensor dimensions for operations like broadcasting.

# Order of Index (Dimension)
Understanding the order of dimensions (or indices) in tensors when performing operations like reshaping is fundamental in PyTorch, as well as in most other rensor-manipulating libraries.

## Dimension Indexing in PyTorch
In PyTorch, tensors are indexed starting from 0. Here's how the dimensions are typically ordered:
* **0th Dimension**: This is often referred to as the "batch" dimension in machine learning contexts, where each element along this axis represents a separate instance in a batch of data.
* **1st Dimension**: In many applications, particularly those dealing with images, this could represent the "channel" dimension (e.g., RGB color channels in an image).
* **2nd and Higher Dimensions**: These usually represent the spatial dimensions (height, width) in images, or sequence length in time series or natural language data.



## Example of Operations
Let's illustrate this with a few examples to show how you would use these indices in practice with operations like **reshape**, **unsqueeze**, and **squeeze**

1. **Reshaping a Tensor**:
    * Suppose you have a 2D tensor representing multiple data points, each with several features, and you want to reshape this into a high-dimensional tensor for a deep learning model.

In [ ]:
import torch

# A tensor woth shape (batch_size, features) = (10, 16)
x = torch.randn(10, 16)

# Reshape the tensor to shape (batch_size, channels, height, width) = (10, 4, 2, 2)
x_reshaped = x.reshape(10, 4, 2, 2)

print("Reshaped tensor shape: ",x_reshaped.shape)

Reshaped tensor shape:  torch.Size([10, 4, 2, 2])


2. **Adding and Removing Dimensions**:
    * You might want to add a singleton dimension to represent the channel for a grayscale image, or squeeze out unnecessary singleton dimensions after some operations.

In [ ]:
# Suppose x is a tensor representing ten grayscale images, shape=(10,28,28)
x = torch.randn(10, 28, 28)
print('original shape: ', x.shape)

# Add a channel dimension
x_with_channel = x.unsqueeze(1) # New shape(10, 1, 28, 28)
print('shape after adding channel dimension: ', x_with_channel.shape)

# Squeeze out the channel dimension
x_without_channel = x_with_channel.squeeze(1) # Returns to original shape = (10, 28, 28)
print('shape after squeezing channel dimension: ', x_without_channel.shape)



original shape:  torch.Size([10, 28, 28])
shape after adding channel dimension:  torch.Size([10, 1, 28, 28])
shape after squeezing channel dimension:  torch.Size([10, 28, 28])


**Index order is calculated by left side(0, 1, ,2, 3, ...).**


## General Rule for Shape Operations
When you're working with these operations, the indices you provide follow the order in which dimensions are listed in your tensor's shape:
* **Index 0** refer to the first dimension (often the batch size).
* **Index 1** refers to the second dimension (often channels in image data or features in tabuler data).
* **Higer indices** continue in the order they appear.



This consistent indexing method allows you to manipulate the shape and dimensions of tensors predictably. Always be sure that any new shape you <u>provide still accounts for the same total number of elements as the the original tensor</u> unless you're adding or removing singleton dimensions, which don't change the total element count.

# How to manipulate `reshape()`
The **reshape** function in PyTorch is a powerful tool for changing the shape of tensors, and using **-1** as one of the dimensions during reshaping is a common and useful technique. The **-1** argument in the **reshape** function acts as a placeholder for an unspecified dimension, and it allows PyTorch to automatically calculate the necessary size for that dimension based on the other specified dimensions and the total number of elements in the tensor.

## How `-1` Works in `reshape`
When you use **-1** in the **reshape** function, PyTorch calculates the size of this dimension so that the total number of elements in the tensor remains constant. You can only use **-1** for one dimension, as having it in multiple places would lead to ambiguity i the shape.


Here's a step-by-step explanation:
1. **Calculate the Total Number of Elements**: First, PyTorch computes the total number of elements in the original tensor.
2. **Fixed Dimensions**: Then, it considers the other dimensions you've specified in the **reshape** call.
3. **Infer the `-1` Dimension**: PyTorch divides the total number of elements by the product of the specified dimensions to determine the size of the dimension given as **-1**.

## Example Usage of `reshape` with `-1`
Let's go through a few examples ti illustrate how you can use **reshape** with **-1**:

In [ ]:
import torch

# Create a tensor of shape (4, 6)
x = torch.arange(24).reshape(4, 6)
print("Original tensor shape:", x.shape)

# Reshape using -1 (infer one dimension)
# Reshape to have 2 rows and let PyTorch calculate the necessary number of culumns
y = x.reshape(2, -1)
# print("\nReshaped tensor(2*?) where ? is calculated automatically:")
print(y)
print("Reshaped tensor shape:", y.shape)

Original tensor shape: torch.Size([4, 6])
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])
Reshaped tensor shape: torch.Size([2, 12])


In [ ]:
# Reshape to have 3 columns and let PyTorch calculate the number of rows
z = x.reshape(-1, 3)
print("\nReshaped tensor(?, 3) where ? is calculated automatically:")
print(z)
print("Reshaped tensor shape:", z.shape)


Reshaped tensor(?, 3) where ? is calculated automatically:
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]])
Reshaped tensor shape: torch.Size([8, 3])


In [ ]:
# More complex rehsaping
# Suppose we want a 3D tensor with the last dimension being 4, PyTorch calculates the rest
print("original shape: ", x.shape)
w = x.reshape(2, 3, -1)
print("Reshaped tensor shape: ", w.shape)


# Reshape to (-1, 2, 6)
b = x.reshape(-1, 2, 6)
print("\nReshaped tensor to (-1, 2, 6):")
print(b)
print("Shape of reshaped tensor:", b.shape)

# Reshape to (4, -1, 3)
c = x.reshape(4, -1, 3)
print("\nReshaped tensor to (4, -1, 3):")
print(c)
print("Shape of reshaped tensor:", c.shape)

original shape:  torch.Size([4, 6])
Reshaped tensor shape:  torch.Size([2, 3, 4])

Reshaped tensor to (-1, 2, 6):
tensor([[[ 0,  1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10, 11]],

        [[12, 13, 14, 15, 16, 17],
         [18, 19, 20, 21, 22, 23]]])
Shape of reshaped tensor: torch.Size([2, 2, 6])

Reshaped tensor to (4, -1, 3):
tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23]]])
Shape of reshaped tensor: torch.Size([4, 2, 3])


## Things to Keep in Mind
* The new shape must be compatible with the number of elements in the original tensor. the product of the new shape dimensions must equal the total number of elements.
* Using **-1** is especially useful when you don't know the exact size of a particular dimension or when the dimension size might change depending on the situation (e.g., variable batch sizes in data processing pipelines).
* You can only use **-1** for one dimension in the shape. If used for more than one dimension, PyTorch will throw an error due to the ambiguity in determining the sizes.

# How to use `view`
**view** function is similar to **reshape** but requires the tensor to be <u>contifuous</u> for the operation to work. As with **reshape**, **view** allows you to change the shape of a tensor without changing its data, but it operates directly on the tensor's storage if the requested view is compatible with the tensor's original stride.

## Basic Usage of `view`
Here are some practical examples using the **view** function to change the shape of tensors. I'll use a tensor with a shape of **(4, 6)** as in the previous examples:

1. **Flattening a Tensor**:
    * You can flatten a tensor to a single dimension. This is often used in neural networks to transform a multi-dimensional input a flat vector for a fully connected layer.
2. **Changing to a Different 2D Shape**:
    * Transform the shape for compatiblility with different operations, such as feeding it into a neural newtwork layer that expects a certain input shape.
3. **Expanding to a 3D Tensor**:
    * Useful for adding a dimension, for instance, to create a batch or a channel dimension.


Let's demonstrate each with the **view** function:

In [ ]:
import torch

# Create a tensor of shape (4, 6)
x = torch.arange(24).reshape(4, 6)
print(x)
print("Original tensor shape:", x.shape)

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])
Original tensor shape: torch.Size([4, 6])


In [ ]:
# Flattening the tensor
flat_x = x.view(-1)
print(flat_x)
print("Flattened tensor shape:", flat_x.shape)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23])
Flattened tensor shape: torch.Size([24])


In [ ]:
# Changing to a different 2D shape (12, 2)
x_view_2d = x.view(12, 2)
print(x_view_2d)
print("Reshaped tensor shape:", x_view_2d.shape)

tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]])
Reshaped tensor shape: torch.Size([12, 2])


In [ ]:
# Expanding to a 3D tensor (2, 4, 3)
x_view_3d = x.view(2, 4, 3)
print(x_view_3d)
print("Reshaped tensor shape:", x_view_3d.shape)

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17],
         [18, 19, 20],
         [21, 22, 23]]])
Reshaped tensor shape: torch.Size([2, 4, 3])


## Notes on Using `view`
* **Contiguity Requirement**: The tensor must be contiguous for **view** to work without errors. If a tensor operation makes the tensor non-contiguous (like transpose or cetrain slices), you may need to call **.contiguous()** before using **view**.
* **`view` vs. `reshape`**: Unlike **reshape**, which can handle non-contiguous tensors by possibly creating a copy, **view** will throw an error if it can't provide a view on the existing data due to contiguity issues.


Here's is how you can ensure contiguity:

In [ ]:
# Suppose x was midified to be non-contiguous
print('Original tensor shape: ', x.shape)
x_transposed = x.transpose(0, 1)
print('transposed tensor: ')
print(x_transposed)
print("transposed tensor shape:", x_transposed.shape)

Original tensor shape:  torch.Size([4, 6])
transposed tensor: 
tensor([[ 0,  6, 12, 18],
        [ 1,  7, 13, 19],
        [ 2,  8, 14, 20],
        [ 3,  9, 15, 21],
        [ 4, 10, 16, 22],
        [ 5, 11, 17, 23]])
transposed tensor shape: torch.Size([6, 4])


In [ ]:
# Trying to view a non-contiguos tensor
try:
    non_contig_view = x_transposed.view(12, 2)
except Exception as e:
    print(e)

view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.


In [ ]:
# Making it contiguous
x_transposed_contiguous = x_transposed.contiguous()
contig_vew = x_transposed_contiguous.view(12, 2)
print(contig_vew)
print('Contiguous and reshaped tensor shape: ', contig_vew.shape)

tensor([[ 0,  6],
        [12, 18],
        [ 1,  7],
        [13, 19],
        [ 2,  8],
        [14, 20],
        [ 3,  9],
        [15, 21],
        [ 4, 10],
        [16, 22],
        [ 5, 11],
        [17, 23]])
Contiguous and reshaped tensor shape:  torch.Size([12, 2])


This example demonstrates the importance of ensuring tensor contiguity when using **view** and how to troubleshoot and fix issues related to non-contiguous tensors.