# Tensor.squeeze()について
* Tensor.squeeze()は「テンソル中の要素数1の次元を削除する」
* Tensor.unsqueeze(d: int)は「テンソルのd階目に要素数1の次元を挿入する」 というものだ。

In [1]:
import torch

# Unsqueeze使用例
* Tensor.unsqueeze(d: int) - テンソルのd階(次元)目に要素数1の次元を挿入する

In [2]:

t = torch.Tensor([[1, 2, 3], [4, 5, 6]])
t

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [3]:
t.shape


torch.Size([2, 3])

In [11]:
# 次元数
t.dim()

2

In [5]:
# 0番目の位置(toch.Size([2,3])の2の前の次元)に次元を追加する
t_us = t.unsqueeze(0)
t_us.shape

torch.Size([1, 2, 3])

In [15]:
t_us.dim()

3

* ↑ 新しく、もう1次元が増えて3次元になった

In [16]:
# 要素数
t_us.numel()

6

In [7]:
# 1番目の位置(行)に次元を追加する
t_us_1 = t.unsqueeze(1)
display(t_us_1)
print('\n')
print(t_us_1.shape)

tensor([[[1., 2., 3.]],

        [[4., 5., 6.]]])



torch.Size([2, 1, 3])


In [12]:
# 次元数
t_us_1.dim()

3

In [14]:
# 要素数
t_us_1.numel()

6

In [8]:
# 2番目の位置(列)に次元を追加する
t_us_2 = t.unsqueeze(2)
display(t_us_2)
print('\n')
print(t_us_2.shape)

tensor([[[1.],
         [2.],
         [3.]],

        [[4.],
         [5.],
         [6.]]])



torch.Size([2, 3, 1])


In [13]:
# 次元数
t_us_2.dim()

3

# Squeeze
* テンソル内の要素数1の次元を削除する

In [17]:
t

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [20]:
t.squeeze()

tensor([[1., 2., 3.],
        [4., 5., 6.]])

 * ↑ 要素数が1の次元がないので変化なし

In [23]:
display(t_us_1)
print('\n', t_us_1.shape)

tensor([[[1., 2., 3.]],

        [[4., 5., 6.]]])


 torch.Size([2, 1, 3])


In [24]:
t_s_1 = t_us_1.squeeze()
display(t_s_1)
print('\n',t_s_1.shape)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


 torch.Size([2, 3])


* ↑ 要素数が1の次元が削除された

In [29]:
display(t_us_2)
print('\n', t_us_2.shape)

tensor([[[1.],
         [2.],
         [3.]],

        [[4.],
         [5.],
         [6.]]])


 torch.Size([2, 3, 1])


In [28]:
t_s_2 = t_us_2.squeeze()
display(t_s_2)
print('\n',t_s_2.shape)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


 torch.Size([2, 3])


* ↑ 要素数が1の次元が削除された

In [39]:
display(t_us_2)
print('\n', t_us_2.shape)

tensor([[[1.],
         [2.],
         [3.]],

        [[4.],
         [5.],
         [6.]]])


 torch.Size([2, 3, 1])


In [40]:
t_s_2_1 = t_us_2.squeeze(-1) # -1で最後の次元の要素数が1なら最後の次元を削除する！！！
display(t_s_2_1)
print('\n',t_s_2_1.shape)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


 torch.Size([2, 3])


* squeeze(-1)で、最後の次元の要素数が1つだけなら、最後の次元を削除する