# Saving and Loading Models
* https://www.youtube.com/watch?v=9L9jEOwRrCg&list=PLqnslRFeH2UrcDBWF5mfPGpqQDSta6VK4&index=17

In [2]:
import torch
import torch.nn as nn

In [ ]:
#### COMPLETE MODEL ####
# モデルをpickleで完全に保存する方法
torch.save(model, PATH)


# load
# model class must be defined somewhere
model = torch.load(PATH)
model.eval()

In [ ]:
#### STATE DICT ####
# パラメータとかのみを保存する方法
torch.save(model.state_dict(), PATH)

# load
# model must be created again with parameters
# なので、モデルのオブジェクトを作る必要がある
model = Model(*args, **kwargs)
model.load_state_dict(torch.load(PATH))
model.eval()

### example

In [4]:
class Model(nn.Module):
  def __init__(self, n_input_features):
    super(Model, self).__init__()
    self.linear = nn.Linear(n_input_features, 1)

  def forward(self, x):
    y_pred = torch.sigmoid(self.linear(x))
    return y_pred

model = Model(n_input_features=6)

In [5]:
# save by lazy version
FILE = '/content/drive/MyDrive/study_DeepLearning/data/y8_model.pth'
torch.save(model, FILE)

In [6]:
# load
model = torch.load(FILE)
model.eval()

for param in model.parameters():
  print(param)

Parameter containing:
tensor([[-0.2738, -0.3894, -0.1800,  0.2639, -0.2662, -0.1015]],
       requires_grad=True)
Parameter containing:
tensor([-0.2083], requires_grad=True)


In [7]:
# save by another way
torch.save(model.state_dict(), FILE)

In [9]:
# load
loaded_model = Model(n_input_features=6)
loaded_model.load_state_dict(torch.load(FILE))
loaded_model.eval()

for param in loaded_model.parameters():
  print(param)

Parameter containing:
tensor([[-0.2738, -0.3894, -0.1800,  0.2639, -0.2662, -0.1015]],
       requires_grad=True)
Parameter containing:
tensor([-0.2083], requires_grad=True)


In [10]:
print(loaded_model.state_dict())

OrderedDict([('linear.weight', tensor([[-0.2738, -0.3894, -0.1800,  0.2639, -0.2662, -0.1015]])), ('linear.bias', tensor([-0.2083]))])


## 学習過程の各チェックポイントも保存する方法

In [11]:
model = Model(n_input_features=6)

learning_rate = 0.01
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)
print(optimizer.state_dict())

{'state': {}, 'param_groups': [{'lr': 0.01, 'momentum': 0, 'dampening': 0, 'weight_decay': 0, 'nesterov': False, 'maximize': False, 'foreach': None, 'differentiable': False, 'params': [0, 1]}]}


In [12]:
checkpoint = {
    "epoch": 90,
    "model_state": model.state_dict(),
    "optim_state": optimizer.state_dict()
}
checkpoint_FILE = '/content/drive/MyDrive/study_DeepLearning/data/checkpoint.pth'
torch.save(checkpoint, checkpoint_FILE)

In [13]:
# checkpointのロード
loaded_checkpoint = torch.load(checkpoint_FILE)
epoch = loaded_checkpoint["epoch"]

In [14]:
model = Model(n_input_features=6)
optimizer = torch.optim.SGD(model.parameters(), lr=0)

model.load_state_dict(checkpoint["model_state"])
optimizer.load_state_dict(checkpoint["optim_state"])

In [15]:
print(optimizer.state_dict())

{'state': {}, 'param_groups': [{'lr': 0.01, 'momentum': 0, 'dampening': 0, 'weight_decay': 0, 'nesterov': False, 'maximize': False, 'foreach': None, 'differentiable': False, 'params': [0, 1]}]}


## GPUの場合

### Save on GPU, Load on CPU

In [ ]:
# save on gpu, load on cpu
device = torch.device("cuda")
model.to(device)
torch.save(model.state_dict(), PATH)

device = torch.device("cpu")
model = Model(*args, **kwargs)
model.load_state_dict(torch.load(PATH, map_location=device))

### Save on GPU, Load on GPU

In [ ]:
# save on gpu, load on gpu
device = torch.device("cuda")
model.to(device)
torch.save(model.satate_dict(), PATH)

model = Model(*args, *:kwargs)
model.load_state_dict(torch.load(PATH))
model.to(device)

### Save on CPU, Load on GPU

In [ ]:
torch.save(model.state_dict(). PATH)

device = torch.device("cuda")
model = Model(*args, **kwargs)
model.load_state_dict(torch.load(PATH, map_location="cuda:0")) # choose what ever GPU numbers
model.to(device)